#!/usr/bin/env python3
import sys
import time

time.sleep(1)

out = sys.argv[1] # adds first argument to output

if(len(sys.argv) > 2): # adds remaining arguments to output
    for i in range(2, len(sys.argv)):
        out = out + " " + sys.argv[i]

print(out + "       # P.S. I wrote this program in PYTHON")
